# Generated by Codex on 2025-12-28
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("icts", "0014_alter_accessproposal_access_code_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="IMPYearCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "IMP year counter",
                "verbose_name_plural": "IMP year counters",
                "ordering": ["year"],
            },
        ),
        migrations.CreateModel(
            name="IMPSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_code", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In progress"), ("completed", "Completed")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notice_pdf", models.FileField(blank=True, null=True, upload_to="imp/notices/")),
                ("final_report_pdf", models.FileField(blank=True, null=True, upload_to="imp/final_reports/")),
                ("final_report_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("request_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "access_proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imp_sessions",
                        to="icts.accessproposal",
                    ),
                ),
                (
                    "final_report_uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imp_final_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imp_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IMP session",
                "verbose_name_plural": "IMP sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IMPSampleRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[("proposal", "Proposal"), ("session", "Session")],
                        default="proposal",
                        max_length=20,
                    ),
                ),
                ("identification", models.CharField(max_length=200)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("details", models.TextField(blank=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("implant_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("destroyed", models.BooleanField(default=False)),
                ("destroyed_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="sigmaimp.impsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "IMP sample record",
                "verbose_name_plural": "IMP sample records",
                "ordering": ["sequence"],
                "unique_together": {("session", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="IMPAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("rawdata", "Raw data"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="imp/attachments/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sigmaimp.impsamplerecord",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sigmaimp.impsession",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imp_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IMP attachment",
                "verbose_name_plural": "IMP attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="impattachment",
            constraint=models.CheckConstraint(
                check=models.Q(session__isnull=False) | models.Q(sample__isnull=False),
                name="imp_attachment_has_owner",
            ),
        ),
    ]
