# Generated by Django 5.0.1 on 2025-09-10 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=200)),
                ('procedencia', models.CharField(blank=True, max_length=200)),
                ('tratamiento_previo', models.CharField(blank=True, max_length=200)),
                ('requisitos_finales', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('corte', models.BooleanField(default=False)),
                ('empastillado', models.BooleanField(default=False)),
                ('lijado', models.BooleanField(default=False)),
                ('pulido', models.BooleanField(default=False)),
                ('electropulido', models.BooleanField(default=False)),
                ('trat_quimico', models.BooleanField(default=False)),
                ('trat_termico', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='Pendiente', max_length=20)),
                ('codigo_muestra', models.CharField(blank=True, help_text='Se puede asignar al aceptar (p.ej. 25-001)', max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avance', 'Avance'), ('nota', 'Nota interna')], default='avance', max_length=10)),
                ('contenido', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='avances/')),
                ('visible_para_usuario', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_publicados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='sigmalab.solicitud')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
