# Generated by Django 5.0.1 on 2025-09-13 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0002_solicitud_avance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='autonomo',
            field=models.BooleanField(default=False, help_text='Usuario validado como autónomo para esta solicitud'),
        ),
        migrations.CreateModel(
            name='DiarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etapa', models.CharField(choices=[('corte', 'Corte'), ('empastillado', 'Empastillado'), ('lijado', 'Lijado'), ('pulido', 'Pulido'), ('electropulido', 'Electropulido'), ('trat_quimico', 'Tratamiento químico'), ('trat_termico', 'Tratamiento térmico'), ('ensayo', 'Ensayo máquina'), ('otra', 'Otra')], max_length=20)),
                ('nota', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='sigmalab.solicitud')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
