# Generated by Django 5.0.1 on 2025-09-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0008_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='croquis',
            field=models.ImageField(blank=True, help_text='Adjuntar croquis', null=True, upload_to='solicitudes/croquis/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='imagen_muestra',
            field=models.ImageField(blank=True, help_text='Adjuntar imagen de la muestra', null=True, upload_to='solicitudes/imagenes/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='manejo_especial',
            field=models.TextField(blank=True, help_text='¿Requiere algún tipo de manejo o protección especial?'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='material_radioactivo',
            field=models.BooleanField(default=False, help_text='¿Es material radiactivo o contaminado?'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numero_muestras',
            field=models.PositiveIntegerField(default=1, help_text='Número de muestras a procesar'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='otro_dato_importante',
            field=models.TextField(blank=True, help_text='Otro dato importante de la muestra'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tratamiento_previo',
            field=models.TextField(blank=True, help_text='¿Se ha realizado algún tratamiento previo?'),
        ),
        migrations.CreateModel(
            name='MuestraIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.PositiveIntegerField(help_text='Número de secuencia (1, 2, 3, etc.)')),
                ('identificacion', models.CharField(help_text='Identificación que le da el usuario', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la muestra')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='sigmalab.solicitud')),
            ],
            options={
                'verbose_name': 'Muestra Individual',
                'verbose_name_plural': 'Muestras Individuales',
                'ordering': ['numero_secuencia'],
                'unique_together': {('solicitud', 'numero_secuencia')},
            },
        ),
    ]
