# Generated by Django 5.0.1 on 2025-09-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0009_solicitud_croquis_solicitud_imagen_muestra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modificacion', models.CharField(choices=[('numero_muestras', 'Cambiar número de muestras'), ('requisitos_finales', 'Modificar requisitos finales'), ('etapas_preparacion', 'Añadir/quitar etapas de preparación'), ('observaciones', 'Modificar observaciones'), ('otro_dato_importante', 'Modificar otros datos importantes'), ('manejo_especial', 'Modificar manejo especial'), ('tratamiento_previo', 'Modificar tratamiento previo'), ('procedencia', 'Modificar procedencia'), ('otro', 'Otra modificación')], help_text='Tipo de modificación solicitada', max_length=50)),
                ('descripcion_cambio', models.TextField(help_text='Descripción detallada del cambio solicitado')),
                ('justificacion', models.TextField(help_text='Justificación del cambio solicitado')),
                ('cambios_solicitados', models.JSONField(default=dict, help_text='Campos específicos que se quieren modificar')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_tecnico', models.TextField(blank=True, help_text='Comentarios del técnico sobre la modificación')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud_original', models.ForeignKey(help_text='Solicitud original que se quiere modificar', on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='sigmalab.solicitud')),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Modificación',
                'verbose_name_plural': 'Solicitudes de Modificación',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
