# Generated by Django 5.0.1 on 2025-09-15 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0010_solicitudmodificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudAnulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(help_text='Justificación de por qué se anula la solicitud')),
                ('fecha_anulacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_anulacion', models.CharField(choices=[('usuario_pendiente', 'Anulación por usuario (solicitud pendiente)'), ('usuario_aceptada', 'Anulación por usuario (solicitud aceptada)'), ('tecnico', 'Anulación por técnico'), ('sistema', 'Anulación automática del sistema')], default='usuario_pendiente', help_text='Tipo de anulación', max_length=20)),
                ('solicitud', models.ForeignKey(help_text='Solicitud que se anula', on_delete=django.db.models.deletion.CASCADE, related_name='anulaciones', to='sigmalab.solicitud')),
                ('usuario_anulacion', models.ForeignKey(help_text='Usuario que anula la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_anuladas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anulación de Solicitud',
                'verbose_name_plural': 'Anulaciones de Solicitudes',
                'ordering': ['-fecha_anulacion'],
            },
        ),
    ]
