# Generated by Django 5.0.1 on 2025-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0011_alter_solicitud_estado_solicitudanulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_estimada_finalizacion',
            field=models.DateTimeField(blank=True, help_text='Fecha calculada de finalización basada en la estimación', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado_indeterminado',
            field=models.BooleanField(default=False, help_text='Marcar si el tiempo de finalización es indeterminado'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado_numero',
            field=models.PositiveIntegerField(blank=True, help_text='Número de unidades de tiempo estimadas (1-30)', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado_unidad',
            field=models.CharField(blank=True, choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], help_text='Unidad de tiempo estimada', max_length=10),
        ),
    ]
