# Generated by Django 5.0.1 on 2025-09-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0012_solicitud_fecha_estimada_finalizacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la incidencia', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la incidencia')),
                ('categoria', models.CharField(choices=[('equipos', 'Equipos'), ('infraestructura', 'Infraestructura'), ('seguridad', 'Seguridad'), ('suministros', 'Suministros'), ('comunicaciones', 'Comunicaciones'), ('otros', 'Otros')], help_text='Categoría de la incidencia', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad de la incidencia', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='pendiente', help_text='Estado actual de la incidencia', max_length=15)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación específica donde ocurrió la incidencia', max_length=100)),
                ('equipos_afectados', models.CharField(blank=True, help_text='Equipos o sistemas afectados', max_length=200)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (imagen, documento, etc.)', null=True, upload_to='incidencias/archivos/')),
                ('impacto_operaciones', models.TextField(blank=True, help_text='Descripción del impacto en las operaciones del laboratorio')),
                ('acciones_inmediatas', models.TextField(blank=True, help_text='Acciones inmediatas tomadas o recomendadas')),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Técnico asignado para resolver la incidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(help_text='Usuario que reportó la incidencia', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia del Laboratorio',
                'verbose_name_plural': 'Incidencias del Laboratorio',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(help_text='Contenido de la respuesta')),
                ('es_resolucion', models.BooleanField(default=False, help_text='Indica si esta respuesta marca la resolución de la incidencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto en la respuesta', null=True, upload_to='incidencias/respuestas/')),
                ('autor', models.ForeignKey(help_text='Usuario que escribió la respuesta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(help_text='Incidencia a la que pertenece esta respuesta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='sigmalab.incidencialaboratorio')),
            ],
            options={
                'verbose_name': 'Respuesta de Incidencia',
                'verbose_name_plural': 'Respuestas de Incidencias',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
