# Generated by Django 5.0.1 on 2025-09-15 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0013_incidencialaboratorio_respuestaincidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del becario', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del becario', max_length=100)),
                ('email', models.EmailField(help_text='Email de contacto del becario', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto (opcional)', max_length=20)),
                ('tipo_becario', models.CharField(choices=[('becario_predoc', 'Becario Predoctoral'), ('becario_postdoc', 'Becario Postdoctoral'), ('estudiante_tfg', 'Estudiante TFG'), ('estudiante_tfm', 'Estudiante TFM'), ('investigador_visitante', 'Investigador Visitante'), ('otro', 'Otro')], help_text='Tipo de becario o colaborador', max_length=50)),
                ('institucion_origen', models.CharField(blank=True, help_text='Institución de origen del becario', max_length=200)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la asociación')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización de la asociación (opcional)', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', help_text='Estado actual de la asociación', max_length=20)),
                ('puede_solicitar_autonomo', models.BooleanField(default=True, help_text='¿Puede el becario realizar solicitudes de forma autónoma?')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el becario')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó esta asociación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='becarios_creados', to=settings.AUTH_USER_MODEL)),
                ('investigador_principal', models.ForeignKey(help_text='Investigador principal responsable del becario', on_delete=django.db.models.deletion.CASCADE, related_name='becarios_asociados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Asociado',
                'verbose_name_plural': 'Usuarios Asociados',
                'ordering': ['-creado_en'],
                'unique_together': {('investigador_principal', 'email')},
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='becario_asociado',
            field=models.ForeignKey(blank=True, help_text='Becario que realizó la solicitud (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_realizadas', to='sigmalab.usuarioasociado'),
        ),
    ]
