# Generated by Django 5.0.1 on 2025-09-15 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0014_usuarioasociado_solicitud_becario_asociado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioasociado',
            name='investigador_principal',
            field=models.ForeignKey(help_text='Usuario DTF responsable del becario externo', on_delete=django.db.models.deletion.CASCADE, related_name='becarios_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
