# Generated by Django 5.0.1 on 2025-09-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0015_alter_usuarioasociado_investigador_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_inicio_trabajo',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del trabajo en el laboratorio', null=True),
        ),
    ]
