# Generated by Django 5.0.1 on 2025-09-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0016_solicitud_fecha_inicio_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(help_text='Asunto del mensaje', max_length=200)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('tipo_mensaje', models.CharField(choices=[('consulta', 'Consulta'), ('informacion', 'Información'), ('recordatorio', 'Recordatorio'), ('urgencia', 'Urgencia'), ('general', 'General')], default='general', help_text='Tipo de mensaje', max_length=20)),
                ('leido', models.BooleanField(default=False, help_text='¿Ha sido leído el mensaje?')),
                ('fecha_leido', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó el mensaje', null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(help_text='Usuario que envía el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, help_text='Solicitud relacionada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='sigmalab.solicitud')),
            ],
            options={
                'verbose_name': 'Mensaje Interno',
                'verbose_name_plural': 'Mensajes Internos',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
