# Generated by Django 5.0.1 on 2025-10-10 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0018_labindicadorcalidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del equipo', max_length=200)),
                ('codigo', models.CharField(help_text='Código único del equipo', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del equipo')),
                ('categoria', models.CharField(choices=[('herramientas', 'Herramientas'), ('instrumentos', 'Instrumentos de Medición'), ('equipos_electronicos', 'Equipos Electrónicos'), ('materiales', 'Materiales'), ('otros', 'Otros')], help_text='Categoría del equipo', max_length=30)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento'), ('deshabilitado', 'Deshabilitado')], default='disponible', help_text='Estado actual del equipo', max_length=20)),
                ('disponible_para_prestamo', models.BooleanField(default=True, help_text='¿Está disponible para préstamo?')),
                ('ubicacion_laboratorio', models.CharField(blank=True, help_text='Ubicación dentro del laboratorio', max_length=100)),
                ('requiere_mantenimiento', models.BooleanField(default=False, help_text='¿Requiere mantenimiento especial?')),
                ('instrucciones_uso', models.TextField(blank=True, help_text='Instrucciones de uso y manejo')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Técnico que creó el registro del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo del Laboratorio',
                'verbose_name_plural': 'Equipos del Laboratorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrestamoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del préstamo')),
                ('fecha_devolucion_estimada', models.DateTimeField(help_text='Fecha estimada de devolución')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, help_text='Fecha real de devolución', null=True)),
                ('dias_prestamo', models.PositiveIntegerField(help_text='Número de días de préstamo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('vencido', 'Vencido'), ('perdido', 'Perdido')], default='activo', help_text='Estado del préstamo', max_length=20)),
                ('proposito_uso', models.TextField(blank=True, help_text='Propósito del uso del equipo')),
                ('observaciones_prestamo', models.TextField(blank=True, help_text='Observaciones del préstamo')),
                ('observaciones_devolucion', models.TextField(blank=True, help_text='Observaciones de la devolución')),
                ('notificacion_enviada_vencimiento', models.BooleanField(default=False, help_text='¿Se envió notificación de vencimiento?')),
                ('notificacion_enviada_retraso', models.BooleanField(default=False, help_text='¿Se envió notificación de retraso?')),
                ('equipo', models.ForeignKey(help_text='Equipo prestado', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='sigmalab.equipolaboratorio')),
                ('tecnico_responsable', models.ForeignKey(help_text='Técnico responsable del laboratorio', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_gestionados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario que solicita el préstamo', on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préstamo de Equipo',
                'verbose_name_plural': 'Préstamos de Equipos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo_realizado', 'Préstamo Realizado'), ('recordatorio_vencimiento', 'Recordatorio de Vencimiento'), ('equipo_vencido', 'Equipo Vencido'), ('equipo_devuelto', 'Equipo Devuelto')], help_text='Tipo de notificación', max_length=30)),
                ('mensaje', models.TextField(help_text='Contenido de la notificación')),
                ('enviada', models.BooleanField(default=False, help_text='¿Fue enviada la notificación?')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha de envío de la notificación', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_prestamos', to=settings.AUTH_USER_MODEL)),
                ('prestamo', models.ForeignKey(help_text='Préstamo relacionado', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='sigmalab.prestamoequipo')),
            ],
            options={
                'verbose_name': 'Notificación de Préstamo',
                'verbose_name_plural': 'Notificaciones de Préstamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
