# Generated by Django 5.0.1 on 2025-10-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmalab', '0019_equipolaboratorio_prestamoequipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secuencia códigos S-LAB',
                'verbose_name_plural': 'Secuencias códigos S-LAB',
            },
        ),
    ]
