# Generated by Django 5.0.1 on 2026-01-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('requested_service', models.CharField(choices=[('SEM', 'SEM'), ('Confocal', 'Confocal'), ('SIMS', 'SIMS'), ('Profilometer', 'Profilometer'), ('Dielectric', 'Dielectric'), ('VDG', 'VDG'), ('OLMAT', 'OLMAT'), ('LML', 'LML'), ('Otro', 'Otro')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('form_pdf', models.FileField(blank=True, null=True, upload_to='direct_requests/%Y/%m/')),
                ('is_digitally_signed', models.BooleanField(default=False)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('received', 'received'), ('forwarded', 'forwarded'), ('closed', 'closed')], default='received', max_length=20)),
            ],
        ),
    ]
