# Generated by Django 5.0.1 on 2026-01-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icts', '0015_accessproposal_changes_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='sigmasims/documents/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SIMSRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sims_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('request_code', models.CharField(blank=True, max_length=64)),
                ('reception_date', models.DateField()),
                ('sample_identification', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('sample_characteristics', models.TextField()),
                ('responsible_name', models.CharField(max_length=255)),
                ('client_requirements', models.TextField()),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('incidents', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('access_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sims_records', to='icts.accessproposal')),
            ],
            options={
                'ordering': ['-reception_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SIMSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('determination', models.CharField(blank=True, max_length=255)),
                ('procedure_used', models.CharField(default='PT-DTF-05', max_length=64)),
                ('technique_text', models.TextField(blank=True)),
                ('sample_description', models.TextField(blank=True)),
                ('measurement_conditions', models.TextField(blank=True)),
                ('results_text', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
                ('access_proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sims_report', to='icts.accessproposal')),
            ],
        ),
        migrations.CreateModel(
            name='SIMSReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sigmasims/reports/files/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sigmasims.simsreport')),
            ],
        ),
        migrations.CreateModel(
            name='SIMSReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sigmasims/reports/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sigmasims.simsreport')),
            ],
        ),
    ]
