# Generated by Django 5.0.1 on 2026-01-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simsrecord',
            name='analysis_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='client_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='reception_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='request_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='sample_identification',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='sims_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
