# Generated by Django 5.0.1 on 2026-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0002_alter_simsrecord_analysis_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIMSEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_reference", models.BooleanField(blank=True, default=False)),
                ("responsible", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("decommission_date", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
