# Generated by Django 5.0.1 on 2026-01-09 00:01

from datetime import date

from django.db import migrations


def seed_equipment(apps, schema_editor):
    SIMSEquipment = apps.get_model("sigmasims", "SIMSEquipment")

    equipment_data = [
        {
            "code": "EQ-DTF-L05-01",
            "description": "Secondary Ion Mass Spectrometer",
            "is_reference": False,
            "responsible": "Mar\u00eda Gonz\u00e1lez Viada",
            "location": (
                "Lab T\u00e9cnicas Fisico-Qu\u00edmicas. "
                "Sala 01, S\u00f3tano 1, Edificio 02"
            ),
            "received_date": date(2012, 10, 1),
            "decommission_date": None,
            "observations": "",
        },
        {
            "code": "EQ-DTF-L05-02",
            "description": "Perfilometer",
            "is_reference": False,
            "responsible": "Mar\u00eda Gonz\u00e1lez Viada",
            "location": (
                "Lab T\u00e9cnicas Fisico-Qu\u00edmicas. "
                "Sala 01, S\u00f3tano 1, Edificio 02"
            ),
            "received_date": date(2011, 7, 1),
            "decommission_date": None,
            "observations": "",
        },
    ]

    for payload in equipment_data:
        SIMSEquipment.objects.get_or_create(code=payload["code"], defaults=payload)


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0003_sims_equipment"),
    ]

    operations = [
        migrations.RunPython(seed_equipment, migrations.RunPython.noop),
    ]
