# Generated by Django 5.0.1 on 2026-01-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0004_seed_sims_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="simsequipment",
            name="brand",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="model",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="serial_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="supplier",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="inventory_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="measurement_magnitude",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="measurement_range",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="breakdown_contact",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="calibration_acceptance_criteria",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="specification_conformity",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="associated_equipment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="technical_characteristics",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="usage_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="validation_data",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="maintenance_required",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="maintenance_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="maintenance_procedure",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="simsequipment",
            name="maintenance_period",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="SIMSEquipmentDocRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sigmasims/equipment/docs/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_refs",
                        to="sigmasims.simsequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SIMSEquipmentIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("operation", models.CharField(max_length=255)),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sigmasims/equipment/incidents/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="sigmasims.simsequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SIMSMaintenanceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=255)),
                ("frequency", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_activities",
                        to="sigmasims.simsequipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SIMSMaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_at", models.DateField()),
                ("code", models.CharField(blank=True, max_length=100)),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("result", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="sigmasims.simsequipment",
                    ),
                ),
            ],
        ),
    ]
