# Generated by Django 5.0.1 on 2026-01-09 00:03

from django.db import migrations, models


def seed_spare_inventory(apps, schema_editor):
    SIMSSparePartInventory = apps.get_model("sigmasims", "SIMSSparePartInventory")

    items = [
        {
            "item_name": "Filamentos para el canon de gas",
            "stock_2024_01": None,
            "stock_2024_06": 6,
            "next_orders": None,
            "actions": "Pedir juntas de repuesto para reparar primaria",
        },
        {
            "item_name": "Filamentos para el detector",
            "stock_2024_01": 1,
            "stock_2024_06": 1,
            "next_orders": None,
            "actions": "",
        },
        {
            "item_name": "Bombas Turbomoleculares",
            "stock_2024_01": None,
            "stock_2024_06": None,
            "next_orders": 2,
            "actions": "",
        },
        {
            "item_name": "Medidores de presion",
            "stock_2024_01": 1,
            "stock_2024_06": 1,
            "next_orders": 1,
            "actions": "",
        },
        {
            "item_name": "Controlador para bombas turbo",
            "stock_2024_01": None,
            "stock_2024_06": None,
            "next_orders": 1,
            "actions": "",
        },
    ]

    for payload in items:
        SIMSSparePartInventory.objects.get_or_create(
            item_name=payload["item_name"],
            defaults=payload,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0005_sims_equipment_extended"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIMSSparePartInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("stock_2024_01", models.IntegerField(blank=True, null=True)),
                ("stock_2024_06", models.IntegerField(blank=True, null=True)),
                ("next_orders", models.IntegerField(blank=True, null=True)),
                ("actions", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["item_name"],
            },
        ),
        migrations.RunPython(seed_spare_inventory, migrations.RunPython.noop),
    ]
