# Generated by Django 5.0.1 on 2026-01-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0006_sims_spare_part_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIMSAnnualPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="SIMSAnnualPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_code", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Mantenimiento"),
                            ("CALIBRATION", "Calibracion"),
                            ("VERIFICATION", "Verificacion"),
                            ("VALIDATION", "Validacion"),
                            ("CONTROL", "Control"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "execution_type",
                    models.CharField(
                        choices=[("INTERNAL", "INTERNO"), ("EXTERNAL", "EXTERNO")],
                        max_length=10,
                    ),
                ),
                ("month_01", models.BooleanField(default=False)),
                ("month_02", models.BooleanField(default=False)),
                ("month_03", models.BooleanField(default=False)),
                ("month_04", models.BooleanField(default=False)),
                ("month_05", models.BooleanField(default=False)),
                ("month_06", models.BooleanField(default=False)),
                ("month_07", models.BooleanField(default=False)),
                ("month_08", models.BooleanField(default=False)),
                ("month_09", models.BooleanField(default=False)),
                ("month_10", models.BooleanField(default=False)),
                ("month_11", models.BooleanField(default=False)),
                ("month_12", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sigmasims.simsequipment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="sigmasims.simsannualplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan__year", "equipment_code", "activity"],
            },
        ),
    ]
