# Generated by Django 5.0.1 on 2026-01-09 00:05

from django.db import migrations


def seed_annual_plan_2024(apps, schema_editor):
    SIMSAnnualPlan = apps.get_model("sigmasims", "SIMSAnnualPlan")
    SIMSAnnualPlanEntry = apps.get_model("sigmasims", "SIMSAnnualPlanEntry")
    SIMSEquipment = apps.get_model("sigmasims", "SIMSEquipment")

    plan, _created = SIMSAnnualPlan.objects.get_or_create(year=2024)

    equipment_map = {
        eq.code: eq
        for eq in SIMSEquipment.objects.filter(code__in=["EQ-DTF-L05-01", "EQ-DTF-L05-02"])
    }

    # NOTE: Verification/validation months can be adjusted if the source Excel differs.
    entries = [
        {
            "equipment_code": "EQ-DTF-L05-01",
            "description": "HIDEN SIMS WORKSTATION",
            "activity": "MAINTENANCE",
            "execution_type": "INTERNAL",
            "month_01": True,
        },
        {
            "equipment_code": "EQ-DTF-L05-01",
            "description": "",
            "activity": "VERIFICATION",
            "execution_type": "INTERNAL",
            "month_06": True,
            "month_11": True,
        },
        {
            "equipment_code": "EQ-DTF-L05-01",
            "description": "",
            "activity": "VALIDATION",
            "execution_type": "INTERNAL",
            "month_12": True,
        },
        {
            "equipment_code": "EQ-DTF-L05-02",
            "description": "Perfilometro",
            "activity": "MAINTENANCE",
            "execution_type": "INTERNAL",
            "month_12": True,
        },
        {
            "equipment_code": "EQ-DTF-L05-02",
            "description": "",
            "activity": "VERIFICATION",
            "execution_type": "INTERNAL",
            "month_01": True,
            "month_06": True,
        },
    ]

    for entry in entries:
        equipment = equipment_map.get(entry["equipment_code"])
        defaults = {
            "description": entry.get("description", ""),
            "equipment": equipment,
            "month_01": entry.get("month_01", False),
            "month_02": entry.get("month_02", False),
            "month_03": entry.get("month_03", False),
            "month_04": entry.get("month_04", False),
            "month_05": entry.get("month_05", False),
            "month_06": entry.get("month_06", False),
            "month_07": entry.get("month_07", False),
            "month_08": entry.get("month_08", False),
            "month_09": entry.get("month_09", False),
            "month_10": entry.get("month_10", False),
            "month_11": entry.get("month_11", False),
            "month_12": entry.get("month_12", False),
        }
        obj, created = SIMSAnnualPlanEntry.objects.get_or_create(
            plan=plan,
            equipment_code=entry["equipment_code"],
            activity=entry["activity"],
            execution_type=entry["execution_type"],
            defaults=defaults,
        )
        if not created and equipment and obj.equipment_id is None:
            obj.equipment = equipment
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sigmasims", "0007_sims_annual_plan"),
    ]

    operations = [
        migrations.RunPython(seed_annual_plan_2024, migrations.RunPython.noop),
    ]
