# Generated by Django 5.0.1 on 2026-01-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0009_sims_annual_plan_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIMSReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código del material de referencia', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='Descripción breve', max_length=255)),
                ('responsible', models.CharField(blank=True, help_text='Responsable del material', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Material activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excel_data', models.JSONField(blank=True, help_text='Datos completos leídos del Excel', null=True)),
            ],
            options={
                'verbose_name': 'Material de Referencia SIMS',
                'verbose_name_plural': 'Materiales de Referencia SIMS',
                'ordering': ['code'],
            },
        ),
    ]
