# Generated by Django 5.0.1 on 2026-01-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0010_simsreferencematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsreferencematerial',
            name='activity',
            field=models.CharField(blank=True, help_text='Actividad', max_length=100),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='associated_documentation',
            field=models.TextField(blank=True, help_text='Documentación asociada (Manual de instrucciones, Procedimientos, etc.)'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='calibration_acceptance_criteria',
            field=models.TextField(blank=True, help_text='Criterio de aceptación calibraciones'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='conformity_verification',
            field=models.TextField(blank=True, help_text='Verificación de la conformidad del MR con la especificación'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='conservation_conditions',
            field=models.TextField(blank=True, help_text='Condiciones de conservación'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='detected_incidents',
            field=models.TextField(blank=True, help_text='Incidencias detectadas'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='emission_rate',
            field=models.CharField(blank=True, help_text='Tasa de emisión', max_length=100),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='emission_type',
            field=models.CharField(blank=True, help_text='Tipo de emisión', max_length=100),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Caducidad', null=True),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='is_pattern',
            field=models.BooleanField(default=False, help_text='¿Es patrón?'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='location',
            field=models.TextField(blank=True, help_text='Localización'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='opening_date',
            field=models.DateField(blank=True, help_text='Fecha apertura (en caso líquidos)', null=True),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='pattern_type',
            field=models.CharField(blank=True, help_text='Tipo de patrón (Primario, Secundario, De trabajo)', max_length=50),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='physical_properties',
            field=models.TextField(blank=True, help_text='Propiedades físicas'),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='reception_date',
            field=models.DateField(blank=True, help_text='Fecha de recepción', null=True),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='reference',
            field=models.CharField(blank=True, help_text='Referencia (inventario, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='supplier',
            field=models.CharField(blank=True, help_text='Proveedor', max_length=255),
        ),
        migrations.AddField(
            model_name='simsreferencematerial',
            name='technical_usage_instructions',
            field=models.TextField(blank=True, help_text='Instrucciones técnicas de uso'),
        ),
        migrations.AlterField(
            model_name='simsreferencematerial',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del material'),
        ),
        migrations.AlterField(
            model_name='simsreferencematerial',
            name='excel_data',
            field=models.JSONField(blank=True, help_text='Datos completos leídos del Excel (cache)', null=True),
        ),
    ]
