# Generated by Django 5.0.1 on 2026-01-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0011_simsreferencematerial_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simsreferencematerial',
            name='pattern_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Primario', 'Primario'), ('Secundario', 'Secundario'), ('De trabajo', 'De trabajo')], help_text='Tipo de patrón', max_length=50),
        ),
    ]
