# Generated by Django 5.0.1 on 2026-01-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0012_alter_simsreferencematerial_pattern_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsrecord',
            name='acquisition_conditions',
            field=models.TextField(blank=True, help_text='Condiciones de la adquisición (en superficie, en profundidad, rango de masas, profundidad, etc.)'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='analysis_observations',
            field=models.TextField(blank=True, help_text='Observaciones del análisis'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='analysis_responsible',
            field=models.CharField(blank=True, help_text='Responsable del análisis', max_length=255),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='ion_beam_verification',
            field=models.TextField(blank=True, help_text='Verificación condiciones Ihaz de iones (Variación I haz <25%)'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='ion_gun_optimization',
            field=models.TextField(blank=True, help_text='Optimización Cañón Iones (O/Cs, Presión vacío, Intensidad de corriente)'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='is_original_sample',
            field=models.BooleanField(default=True, help_text='¿La muestra estaba incluida en la propuesta original?'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='report_code',
            field=models.CharField(blank=True, help_text='Código del informe (IN-DTF-SIMS-aa-nn)', max_length=100),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='report_delivery_date',
            field=models.DateField(blank=True, help_text='Fecha de entrega del informe', null=True),
        ),
    ]
