# Generated by Django 5.0.1 on 2026-01-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0013_simsrecord_acquisition_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsrecord',
            name='is_discarded',
            field=models.BooleanField(default=False, help_text='La muestra se desecha (no se devuelve al cliente)'),
        ),
    ]
