# Generated by Django 5.0.1 on 2026-01-11 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0014_simsrecord_is_discarded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simsrecord',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Muestra eliminada/cancelada del estudio'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='removal_reason',
            field=models.TextField(blank=True, help_text='Motivo de eliminación (obligatorio si se elimina)'),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación', null=True),
        ),
        migrations.AddField(
            model_name='simsrecord',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que eliminó la muestra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sims_records_removed', to=settings.AUTH_USER_MODEL),
        ),
    ]
