# Generated by Django 5.0.1 on 2026-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0015_add_record_removal_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simsrecord',
            name='client_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='simsrecord',
            name='sample_characteristics',
            field=models.TextField(blank=True),
        ),
    ]
