# Generated by Django 5.0.1 on 2026-01-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasims', '0016_make_record_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='simsreport',
            name='analysis_date',
            field=models.DateField(blank=True, help_text='Fecha definitiva de análisis', null=True),
        ),
        migrations.AddField(
            model_name='simsreport',
            name='entry_date',
            field=models.DateField(blank=True, help_text='Fecha de entrada (cuando se acepta la propuesta)', null=True),
        ),
        migrations.AddField(
            model_name='simsreport',
            name='technique',
            field=models.CharField(blank=True, choices=[('d_sims_positivo_o', 'D SIMS positivo con O+'), ('d_sims_negativo_cs', 'D SIMS negativo con Cs-')], help_text='Técnica utilizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='simsreport',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Fecha de entrega del informe', null=True),
        ),
        migrations.AlterField(
            model_name='simsreport',
            name='determination',
            field=models.CharField(blank=True, help_text='Determinación', max_length=255),
        ),
        migrations.AlterField(
            model_name='simsreport',
            name='procedure_used',
            field=models.CharField(default='PT-DTF-05', help_text='Procedimiento utilizado', max_length=64),
        ),
    ]
