# Generated by Django 5.0.1 on 2025-09-16 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icts', '0007_ictsuserprofile_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('sem', 'SEM'), ('fib', 'FIB')], help_text='Tipo de análisis: SEM o FIB', max_length=3)),
                ('registration_number', models.CharField(help_text='Número de registro único', max_length=20, unique=True)),
                ('sample_identification', models.CharField(help_text='Identificación de la muestra', max_length=200)),
                ('sample_name', models.CharField(help_text='Nombre de la muestra', max_length=200)),
                ('analysis_date', models.DateField(help_text='Fecha del análisis')),
                ('completion_date', models.DateField(blank=True, help_text='Fecha de finalización', null=True)),
                ('client', models.CharField(help_text='Nombre del cliente (solicitante)', max_length=200)),
                ('sample_characteristics', models.TextField(blank=True, help_text='Características de la muestra')),
                ('client_requirements', models.TextField(blank=True, help_text='Requerimientos del cliente')),
                ('observations', models.TextField(blank=True, help_text='Observaciones del técnico')),
                ('report_code', models.CharField(help_text='Código del informe (PT-DTF-XXX)', max_length=20, unique=True)),
                ('report_files', models.JSONField(blank=True, default=list, help_text='Lista de archivos del informe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_proposal', models.ForeignKey(help_text='Propuesta ICTS asociada', on_delete=django.db.models.deletion.CASCADE, related_name='sem_analyses', to='icts.accessproposal')),
                ('technician', models.ForeignKey(help_text='Técnico responsable', on_delete=django.db.models.deletion.CASCADE, related_name='sem_analyses_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis SEM/FIB',
                'verbose_name_plural': 'Análisis SEM/FIB',
                'ordering': ['-analysis_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEMSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(help_text='Identificación de la muestra', max_length=200)),
                ('name', models.CharField(help_text='Nombre de la muestra', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción de la muestra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(help_text='Análisis asociado', on_delete=django.db.models.deletion.CASCADE, related_name='additional_samples', to='sigmasem.semanalysis')),
            ],
            options={
                'verbose_name': 'Muestra SEM/FIB',
                'verbose_name_plural': 'Muestras SEM/FIB',
            },
        ),
    ]
