# Generated by Django 5.0.1 on 2025-09-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmasem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semanalysis',
            name='sample_identification',
        ),
        migrations.RemoveField(
            model_name='semanalysis',
            name='sample_name',
        ),
        migrations.AddField(
            model_name='semanalysis',
            name='samples_data',
            field=models.JSONField(default=list, help_text='Lista de muestras asociadas al análisis'),
        ),
        migrations.AddField(
            model_name='semanalysis',
            name='session_comments',
            field=models.TextField(blank=True, help_text='Comentarios y observaciones durante la sesión'),
        ),
        migrations.AddField(
            model_name='semanalysis',
            name='session_status',
            field=models.CharField(choices=[('in_progress', 'En Progreso'), ('completed', 'Completada')], default='in_progress', help_text='Estado de la sesión de análisis', max_length=20),
        ),
        migrations.AlterField(
            model_name='semanalysis',
            name='report_code',
            field=models.CharField(help_text='Código del informe (IN-SEM-XX-XXX)', max_length=20, unique=True),
        ),
    ]
