# Generated by Django 5.0.1 on 2025-09-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MecSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('tratamientos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MecSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_durometro', models.BooleanField(default=False)),
                ('equipo_maquina', models.BooleanField(default=False)),
                ('durometro_carga', models.CharField(blank=True, max_length=50)),
                ('durometro_huellas_filas', models.IntegerField(blank=True, null=True)),
                ('durometro_huellas_columnas', models.IntegerField(blank=True, null=True)),
                ('durometro_posicion', models.CharField(blank=True, max_length=200)),
                ('maquina_tipo', models.CharField(blank=True, choices=[('traccion', 'Tracción'), ('fatiga', 'Fatiga'), ('creep-fatiga', 'Creep-Fatiga')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('muestras', models.ManyToManyField(blank=True, to='mec.mecsample')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mec_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mec_solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
