# Generated by Django 5.0.1 on 2025-09-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='durometro_carga',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='durometro_huellas_columnas',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='durometro_huellas_filas',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='durometro_posicion',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='equipo_durometro',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='equipo_maquina',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='maquina_tipo',
        ),
        migrations.RemoveField(
            model_name='mecsolicitud',
            name='muestras',
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_eps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_eps_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_frecuencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_mantenimiento_en',
            field=models.CharField(blank=True, help_text='maxima/minima', max_length=20),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_mantenimiento_tipo',
            field=models.CharField(blank=True, help_text='carga/deformacion', max_length=20),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_porcentaje_deformacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='creep_tiempo_mantenimiento_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='dureza_carga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='dureza_huellas_columnas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='dureza_huellas_filas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='ensayo_creep_fatiga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='ensayo_dureza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='ensayo_fatiga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='ensayo_traccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='fatiga_eps_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='fatiga_eps_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='fatiga_frecuencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='fatiga_porcentaje_deformacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='fatiga_temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='numero_muestras',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='procedencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='traccion_diametro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='traccion_longitud_marca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='traccion_temperatura',
            field=models.CharField(blank=True, help_text='Una por muestra, separadas por coma o línea', max_length=200),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='traccion_velocidad_deformacion',
            field=models.FloatField(blank=True, help_text='s^-1', null=True),
        ),
        migrations.AddField(
            model_name='mecsolicitud',
            name='tratamientos',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MecMuestraNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres', to='mec.mecsolicitud')),
            ],
        ),
    ]
