# Generated by Django 5.0.1 on 2025-09-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mec', '0004_mecmensaje_mecnecesidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MecIndicadorCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(help_text='Fecha de recepción de la muestra')),
                ('fecha_finalizacion_analisis', models.DateTimeField(blank=True, help_text='Fecha de finalización del análisis', null=True)),
                ('fecha_entrega_informe', models.DateTimeField(blank=True, help_text='Fecha de entrega del informe', null=True)),
                ('i1_tiempo_analisis_dias', models.FloatField(blank=True, help_text='I1: Tiempo de ejecución del análisis (días)', null=True)),
                ('i2_tiempo_entrega_dias', models.FloatField(blank=True, help_text='I2: Tiempo de entrega del informe (días)', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='mec.mecsolicitud')),
            ],
            options={
                'verbose_name': 'Indicador de Calidad MEC',
                'verbose_name_plural': 'Indicadores de Calidad MEC',
                'ordering': ['-creado_en'],
            },
        ),
    ]
