# Generated by Django 5.2.5 on 2025-09-23 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticsSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la muestra', max_length=200)),
                ('tipo', models.CharField(blank=True, help_text='Tipo de material', max_length=100)),
                ('tratamientos', models.TextField(blank=True, help_text='Tratamientos previos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpticsSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(help_text='Material', max_length=200)),
                ('numero_muestras', models.PositiveIntegerField(default=1, help_text='Nº muestras')),
                ('referencia_muestras', models.CharField(blank=True, help_text='Ref. muestras', max_length=200)),
                ('tamano', models.CharField(blank=True, help_text='Tamaño', max_length=200)),
                ('medidas_realizar', models.CharField(choices=[('uv_vis', 'UV – VIS'), ('ftir', 'FTIR')], help_text='Medidas a realizar', max_length=10)),
                ('elemento', models.CharField(blank=True, choices=[('H', 'H'), ('Li', 'Li'), ('Be', 'Be'), ('B', 'B'), ('C', 'C'), ('N', 'N'), ('O', 'O'), ('F', 'F'), ('Na', 'Na'), ('Mg', 'Mg'), ('Al', 'Al'), ('Si', 'Si'), ('P', 'P'), ('S', 'S'), ('Cl', 'Cl'), ('K', 'K'), ('Ca', 'Ca'), ('Ti', 'Ti'), ('V', 'V'), ('Cr', 'Cr'), ('Mn', 'Mn'), ('Fe', 'Fe'), ('Co', 'Co'), ('Ni', 'Ni'), ('Cu', 'Cu'), ('Zn', 'Zn'), ('Ga', 'Ga'), ('Ge', 'Ge'), ('As', 'As'), ('Se', 'Se'), ('Br', 'Br'), ('Rb', 'Rb'), ('Sr', 'Sr'), ('Y', 'Y'), ('Zr', 'Zr'), ('Nb', 'Nb'), ('Mo', 'Mo'), ('Tc', 'Tc'), ('Ru', 'Ru'), ('Rh', 'Rh'), ('Pd', 'Pd'), ('Ag', 'Ag'), ('Cd', 'Cd'), ('In', 'In'), ('Sn', 'Sn'), ('Sb', 'Sb'), ('Te', 'Te'), ('I', 'I'), ('Cs', 'Cs'), ('Ba', 'Ba'), ('La', 'La'), ('Ce', 'Ce'), ('Pr', 'Pr'), ('Nd', 'Nd'), ('Pm', 'Pm'), ('Sm', 'Sm'), ('Eu', 'Eu'), ('Gd', 'Gd'), ('Tb', 'Tb'), ('Dy', 'Dy'), ('Ho', 'Ho'), ('Er', 'Er'), ('Tm', 'Tm'), ('Yb', 'Yb'), ('Lu', 'Lu'), ('Hf', 'Hf'), ('Ta', 'Ta'), ('W', 'W'), ('Re', 'Re'), ('Os', 'Os'), ('Ir', 'Ir'), ('Pt', 'Pt'), ('Au', 'Au'), ('Hg', 'Hg'), ('Tl', 'Tl'), ('Pb', 'Pb'), ('Bi', 'Bi'), ('Po', 'Po'), ('At', 'At'), ('Rn', 'Rn'), ('Fr', 'Fr'), ('Ra', 'Ra'), ('Ac', 'Ac'), ('Th', 'Th'), ('Pa', 'Pa'), ('U', 'U'), ('Np', 'Np'), ('Pu', 'Pu'), ('Am', 'Am'), ('Cm', 'Cm'), ('Bk', 'Bk'), ('Cf', 'Cf'), ('Es', 'Es'), ('Fm', 'Fm'), ('Md', 'Md'), ('No', 'No'), ('Lr', 'Lr')], help_text='Elija un elemento', max_length=3)),
                ('otros_datos', models.TextField(blank=True, help_text='Otros datos de interés o información relevante de la/s muestra/s')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('codigo_analisis', models.CharField(blank=True, help_text='Código generado automáticamente (ej: 2025-01)', max_length=20, unique=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optics_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='optics_solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Óptica',
                'verbose_name_plural': 'Solicitudes Ópticas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpticsResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_informe', models.CharField(help_text='Código del informe (PT-DTF-07-F03-CODIGO_ANALISIS)', max_length=50, unique=True)),
                ('archivo_resultado', models.FileField(help_text='Archivo de resultados', upload_to='optics/resultados/')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del técnico')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optics_resultados_creados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='sigmaoptics.opticssolicitud')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpticsMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.PositiveIntegerField(help_text='Número de secuencia')),
                ('identificacion', models.CharField(help_text='Identificación de la muestra', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la muestra')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='sigmaoptics.opticssolicitud')),
            ],
            options={
                'ordering': ['numero_secuencia'],
                'unique_together': {('solicitud', 'numero_secuencia')},
            },
        ),
    ]
