# Generated by Django 5.2.6 on 2025-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmaoptics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticssolicitud',
            name='elemento',
        ),
        migrations.RemoveField(
            model_name='opticssolicitud',
            name='tamano',
        ),
        migrations.AddField(
            model_name='opticssolicitud',
            name='diametro_muestra',
            field=models.FloatField(blank=True, help_text='Diámetro de la muestra en cm', null=True),
        ),
        migrations.AddField(
            model_name='opticssolicitud',
            name='formato_resultado',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('archivo_texto', 'Archivo de texto'), ('ambos', 'Ambos')], default='ambos', help_text='Formato de resultados deseados', max_length=15),
        ),
        migrations.AddField(
            model_name='opticssolicitud',
            name='lado1_muestra',
            field=models.FloatField(blank=True, help_text='Lado 1 de la muestra en cm', null=True),
        ),
        migrations.AddField(
            model_name='opticssolicitud',
            name='lado2_muestra',
            field=models.FloatField(blank=True, help_text='Lado 2 de la muestra en cm', null=True),
        ),
        migrations.AddField(
            model_name='opticssolicitud',
            name='tipo_tamano',
            field=models.CharField(choices=[('diametro', 'Diámetro'), ('lados', 'Lados')], default='diametro', help_text='Tipo de medida de tamaño', max_length=10),
        ),
    ]
