# Generated by Django 5.2.6 on 2025-09-23 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmaoptics', '0002_add_new_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticsAnalisisDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del análisis', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del análisis')),
                ('archivo_datos', models.FileField(help_text='Archivo de datos original', upload_to='optics_analisis/datos/')),
                ('tipo_archivo', models.CharField(choices=[('txt', 'Archivo de texto (.txt)'), ('csv', 'Archivo CSV (.csv)'), ('tsv', 'Archivo TSV (.tsv)'), ('dat', 'Archivo de datos (.dat)')], default='txt', max_length=10)),
                ('separador', models.CharField(default='\t', help_text='Separador de columnas', max_length=10)),
                ('decimal', models.CharField(default=',', help_text='Separador decimal', max_length=5)),
                ('codificacion', models.CharField(default='cp1252', help_text='Codificación del archivo', max_length=20)),
                ('mostrar_espectro', models.BooleanField(default=True, help_text='Mostrar gráfica de espectro')),
                ('mostrar_transmitancia', models.BooleanField(default=True, help_text='Mostrar gráfica de transmitancia')),
                ('mostrar_absorbancia', models.BooleanField(default=True, help_text='Mostrar gráfica de absorbancia')),
                ('mostrar_overview', models.BooleanField(default=True, help_text='Mostrar gráfica general')),
                ('archivo_csv_limpio', models.FileField(blank=True, null=True, upload_to='optics_analisis/csv/')),
                ('archivo_espectro', models.FileField(blank=True, null=True, upload_to='optics_analisis/graficas/')),
                ('archivo_transmitancia', models.FileField(blank=True, null=True, upload_to='optics_analisis/graficas/')),
                ('archivo_absorbancia', models.FileField(blank=True, null=True, upload_to='optics_analisis/graficas/')),
                ('archivo_overview', models.FileField(blank=True, null=True, upload_to='optics_analisis/graficas/')),
                ('duracion_minutos', models.FloatField(blank=True, help_text='Duración del análisis en minutos', null=True)),
                ('num_muestras', models.IntegerField(blank=True, help_text='Número de muestras procesadas', null=True)),
                ('columnas_detectadas', models.TextField(blank=True, help_text='Columnas detectadas en el archivo')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(blank=True, help_text='Solicitud óptica asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_datos', to='sigmaoptics.opticssolicitud')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optics_analisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Datos Ópticos',
                'verbose_name_plural': 'Análisis de Datos Ópticos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
