# Generated by Django 5.0.1 on 2025-09-13 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTFUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ciemat', models.BooleanField(default=False)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('telefono_interno', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dtf_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
