# Generated by Django 5.0.1 on 2025-09-14 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfuserprofile',
            name='info_importante_completada',
            field=models.BooleanField(default=False, help_text='Ha completado la lectura de información importante'),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='info_importante_fin',
            field=models.DateTimeField(blank=True, help_text='Hora de finalización de acceso a información importante', null=True),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='info_importante_inicio',
            field=models.DateTimeField(blank=True, help_text='Hora de inicio de acceso a información importante', null=True),
        ),
        migrations.CreateModel(
            name='InfoImportanteAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('seguridad', 'Seguridad'), ('uso_equipos', 'Uso de Equipos'), ('normas_obligatorias', 'Normas Obligatorias')], max_length=20)),
                ('accedido_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_info_importante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accedido_en'],
                'unique_together': {('user', 'seccion')},
            },
        ),
    ]
