# Generated by Django 5.0.1 on 2025-09-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0002_dtfuserprofile_info_importante_completada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfuserprofile',
            name='acceso_s_lab_restringido',
            field=models.BooleanField(default=False, help_text='Acceso a S-LAB restringido por técnico'),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='acceso_s_mec_restringido',
            field=models.BooleanField(default=False, help_text='Acceso a S-MEC restringido por técnico'),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='motivo_restriccion',
            field=models.TextField(blank=True, help_text='Motivo de la restricción de acceso'),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='restriccion_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha de aplicación de la restricción', null=True),
        ),
        migrations.AddField(
            model_name='dtfuserprofile',
            name='restriccion_por',
            field=models.ForeignKey(blank=True, help_text='Técnico que aplicó la restricción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricciones_aplicadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
