# Generated by Django 5.0.1 on 2025-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0003_dtfuserprofile_acceso_s_lab_restringido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfuserprofile',
            name='division_unidad',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
