# Generated by Django 5.0.1 on 2025-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0004_dtfuserprofile_division_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfuserprofile',
            name='acceso_s_dp_restringido',
            field=models.BooleanField(default=False, help_text='Acceso a S-DP restringido por técnico'),
        ),
    ]
