# Generated by Django 5.0.1 on 2025-09-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0005_dtfuserprofile_acceso_s_dp_restringido'),
    ]

    operations = [
    ]
