# Generated by Django 5.0.1 on 2026-01-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0006_auto_20250915_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfuserprofile',
            name='acceso_s_optics_restringido',
            field=models.BooleanField(default=False, help_text='Acceso a S-OPTICS restringido por técnico'),
        ),
    ]
