# Generated by Django 5.0.1 on 2026-01-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0007_dtfuserprofile_acceso_s_optics_restringido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtfuserprofile',
            name='acceso_s_optics_restringido',
            field=models.BooleanField(default=False, help_text='Acceso a S-OPTICS restringido por tecnico'),
        ),
    ]
