# Generated by Django 5.0.1 on 2025-09-11 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTSUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(blank=True, max_length=150, verbose_name='Centro / Institución')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('validated', models.BooleanField(default=False, verbose_name='Validado por responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icts_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
