# Generated by Django 5.0.1 on 2025-09-11 18:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0002_ictsuserprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='full_name',
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='access_code',
            field=models.CharField(blank=True, help_text='Auto-generated access code', max_length=20),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='applicant_is_different',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_confocal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_imp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_profilometer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_sem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_sem_fib',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_sims',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='facility_vdg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='funding_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='is_new_request',
            field=models.BooleanField(default=True, help_text='Is this a new request?'),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='organization',
            field=models.CharField(blank=True, help_text='Center/Institution', max_length=200),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='previous_access',
            field=models.ForeignKey(blank=True, help_text='Previous approved request to copy data from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='icts.accessproposal'),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='previous_experiments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='project_type',
            field=models.CharField(blank=True, help_text='International, European, National, Regional', max_length=100),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessproposal',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, help_text='Address'),
        ),
        migrations.AddField(
            model_name='participant',
            name='center',
            field=models.CharField(blank=True, help_text='Center/Institution', max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Full name of participant', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='feasibility_ok',
            field=models.BooleanField(blank=True, help_text='Is this proposal technically feasible?', null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='score_industrial_potential',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Industrial potential score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='score_need_infrastructure',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Need for advanced infrastructure score (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='proposalreview',
            name='score_scientific_quality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Scientific quality score (1-5)', null=True),
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document name', max_length=200)),
                ('file', models.FileField(upload_to='proposal_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='icts.accessproposal')),
            ],
        ),
    ]
