# Generated by Django 5.0.1 on 2025-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0003_remove_participant_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictsuserprofile',
            name='user_siglas',
            field=models.CharField(blank=True, null=True, max_length=10, unique=True, verbose_name='Siglas usuario'),
        ),
        migrations.AlterField(
            model_name='accessproposal',
            name='access_code',
            field=models.CharField(blank=True, help_text='Auto-generated access code', max_length=50),
        ),
        migrations.AlterField(
            model_name='accessproposal',
            name='project_type',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('european', 'European'), ('national', 'National'), ('regional', 'Regional')], help_text='International, European, National, Regional', max_length=100),
        ),
    ]
