# Generated by Django 5.0.1 on 2025-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0006_accessproposal_facility_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ictsuserprofile',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula CIEMAT'),
        ),
    ]
