# Generated by Django 5.0.1 on 2025-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0007_ictsuserprofile_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessproposal',
            name='facility_olmat',
            field=models.BooleanField(default=False),
        ),
    ]
