# Generated by Django 5.0.1 on 2025-09-22 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0008_accessproposal_facility_olmat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLMATRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('technical', 'Servicio técnico (5.000 €)'), ('research', 'Servicio de investigación (10.305 €)')], help_text='Tipo de servicio solicitado', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('irradiation_requirements', models.TextField(blank=True, help_text='Requisitos de irradiación de la carga de calor')),
                ('diagnostics_needed', models.JSONField(default=list, help_text='Diagnósticos necesarios (termopares, pirometría, etc.)')),
                ('sample_preparation', models.JSONField(default=list, help_text='Preparación de muestras requerida')),
                ('beam_usage', models.JSONField(default=list, help_text='Uso de haz (NBI, láser, ambos)')),
                ('preferred_dates', models.CharField(blank=True, help_text='Fechas preferidas para el experimento', max_length=200)),
                ('flexibility', models.CharField(choices=[('high', 'Alta flexibilidad'), ('medium', 'Flexibilidad media'), ('low', 'Baja flexibilidad')], default='medium', max_length=20)),
                ('additional_requirements', models.TextField(blank=True, help_text='Requisitos adicionales específicos')),
                ('evaluation_notes', models.TextField(blank=True, help_text='Notas de evaluación del equipo OLMAT')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Coste estimado del servicio', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='olmat_request', to='icts.accessproposal')),
            ],
        ),
    ]
