# Generated by Django 5.0.1 on 2026-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0009_olmatrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessproposal',
            name='facility_optics',
            field=models.BooleanField(default=False),
        ),
    ]
