# Generated by Django 5.0.1 on 2025-12-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icts", "0009_olmatrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="olmatrequest",
            name="activity_description",
            field=models.TextField(
                blank=True,
                help_text="Descripción breve (1-2 páginas) con motivación, objetivos y alcance",
            ),
        ),
        migrations.AddField(
            model_name="olmatrequest",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public", "Entidad pública"),
                    ("private", "Entidad privada"),
                    ("mixed", "Entidad mixta / otra"),
                ],
                default="",
                help_text="Naturaleza de la entidad (pública/privada/mixta)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="olmatrequest",
            name="proponent_affiliation",
            field=models.CharField(
                blank=True, help_text="Afiliación del proponente", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="olmatrequest",
            name="proponent_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del proponente o investigador principal",
                max_length=200,
            ),
        ),
    ]
