# Generated by Django 5.0.1 on 2025-12-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icts", "0010_olmatrequest_activity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="olmatrequest",
            name="access_code",
            field=models.CharField(
                blank=True,
                max_length=120,
                help_text="Código específico de la solicitud OLMAT",
            ),
        ),
    ]
