# Generated by Django 5.0.1 on 2025-12-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icts", "0011_olmatrequest_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessproposal",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessproposal",
            name="user_sequence_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ictsuserprofile",
            name="proposal_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="accessproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(user_sequence_number__isnull=False),
                fields=("applicant", "user_sequence_number"),
                name="unique_accessproposal_user_sequence",
            ),
        ),
    ]
