# Generated by Django 5.0.1 on 2025-12-17

from django.db import migrations
from django.db.models import Count


def forwards(apps, schema_editor):
    AccessProposal = apps.get_model("icts", "AccessProposal")
    ICTSUserProfile = apps.get_model("icts", "ICTSUserProfile")

    ICTSUserProfile.objects.update(proposal_counter=0)

    counts = (
        AccessProposal.objects.exclude(status="draft")
        .values("applicant_id")
        .annotate(cnt=Count("id"))
    )

    for row in counts:
        user_id = row["applicant_id"]
        count = row["cnt"]
        profile, _ = ICTSUserProfile.objects.get_or_create(user_id=user_id)
        ICTSUserProfile.objects.filter(pk=profile.pk).update(proposal_counter=count)

    for row in counts:
        user_id = row["applicant_id"]
        proposals = (
            AccessProposal.objects.filter(applicant_id=user_id)
            .exclude(status="draft")
            .order_by("created_at", "id")
        )
        used = set(
            p.user_sequence_number
            for p in proposals
            if p.user_sequence_number is not None
        )
        seq = 1
        for proposal in proposals:
            if proposal.user_sequence_number is not None:
                continue
            while seq in used:
                seq += 1
            AccessProposal.objects.filter(pk=proposal.pk).update(
                user_sequence_number=seq
            )
            used.add(seq)
            seq += 1


class Migration(migrations.Migration):
    dependencies = [
        ("icts", "0012_accessproposal_submission_fields"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
