# Generated by Django 5.0.1 on 2025-12-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icts", "0013_backfill_proposal_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessproposal",
            name="access_code",
            field=models.CharField(blank=True, help_text="Auto-generated access code", max_length=80),
        ),
    ]
