# Generated by Django 5.0.1 on 2026-01-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0010_accessproposal_facility_optics'),
        ('icts', '0018_proposalreview_mod_requests'),
    ]

    operations = [
    ]
