# Generated by Django 5.0.1 on 2026-01-10 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icts', '0019_merge_20260110_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ictsuserprofile',
            name='user_siglas',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Siglas usuario'),
        ),
        migrations.AddConstraint(
            model_name='ictsuserprofile',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('user_siglas__isnull', True), _negated=True), models.Q(('user_siglas', ''), _negated=True)), fields=('user_siglas',), name='unique_non_null_user_siglas'),
        ),
    ]
