# Generated by Django 5.0.1 on 2025-09-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DpMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DpNecesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DpSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('tratamientos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DpSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=200)),
                ('procedencia', models.CharField(blank=True, max_length=200)),
                ('numero_muestras', models.PositiveIntegerField(default=1)),
                ('tratamientos', models.TextField(blank=True)),
                ('ensayo_desorcion', models.BooleanField(default=False)),
                ('desorcion_temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('desorcion_tiempo', models.FloatField(blank=True, help_text='Tiempo en horas', null=True)),
                ('desorcion_presion', models.FloatField(blank=True, help_text='Presión en bar', null=True)),
                ('desorcion_gas', models.CharField(blank=True, help_text='Gas utilizado (H2, D2, etc.)', max_length=100)),
                ('desorcion_volumen_muestra', models.FloatField(blank=True, help_text='Volumen de muestra en cm³', null=True)),
                ('ensayo_permeacion', models.BooleanField(default=False)),
                ('permeacion_temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('permeacion_presion_alta', models.FloatField(blank=True, help_text='Presión lado alto en bar', null=True)),
                ('permeacion_presion_baja', models.FloatField(blank=True, help_text='Presión lado bajo en bar', null=True)),
                ('permeacion_gas', models.CharField(blank=True, help_text='Gas utilizado (H2, D2, etc.)', max_length=100)),
                ('permeacion_espesor_membrana', models.FloatField(blank=True, help_text='Espesor de membrana en mm', null=True)),
                ('permeacion_area_membrana', models.FloatField(blank=True, help_text='Área de membrana en cm²', null=True)),
                ('ensayo_difusion', models.BooleanField(default=False)),
                ('difusion_temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('difusion_tiempo', models.FloatField(blank=True, help_text='Tiempo en horas', null=True)),
                ('difusion_concentracion_inicial', models.FloatField(blank=True, help_text='Concentración inicial en ppm', null=True)),
                ('difusion_concentracion_final', models.FloatField(blank=True, help_text='Concentración final en ppm', null=True)),
                ('difusion_volumen_solucion', models.FloatField(blank=True, help_text='Volumen de solución en ml', null=True)),
                ('ensayo_adsorcion', models.BooleanField(default=False)),
                ('adsorcion_temperatura', models.FloatField(blank=True, help_text='Temperatura en °C', null=True)),
                ('adsorcion_presion', models.FloatField(blank=True, help_text='Presión en bar', null=True)),
                ('adsorcion_gas', models.CharField(blank=True, help_text='Gas utilizado', max_length=100)),
                ('adsorcion_masa_muestra', models.FloatField(blank=True, help_text='Masa de muestra en mg', null=True)),
                ('adsorcion_area_superficie', models.FloatField(blank=True, help_text='Área superficial en m²/g', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dp_solicitudes', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dp_solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DpMuestraNombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nombres', to='sigmadp.dpsolicitud')),
            ],
        ),
        migrations.CreateModel(
            name='DpEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='sigmadp.dpsolicitud')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
