# Generated by Django 5.0.1 on 2025-09-19 02:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmadp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DpSolicitudTermica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_muestra', models.CharField(help_text='Nombre de la muestra', max_length=200)),
                ('material', models.CharField(help_text='Material de la muestra', max_length=200)),
                ('temperatura_maxima', models.FloatField(help_text='Temperatura máxima del ensayo [ºC]', validators=[django.core.validators.MaxValueValidator(900, 'La temperatura máxima no puede superar 900ºC')])),
                ('tasa_calentamiento', models.FloatField(help_text='Tasa de calentamiento [ºC/min]', validators=[django.core.validators.MaxValueValidator(15, 'La tasa de calentamiento no puede superar 15ºC/min')])),
                ('tasa_enfriamiento', models.FloatField(help_text='Tasa de enfriamiento [ºC/min]', validators=[django.core.validators.MaxValueValidator(15, 'La tasa de enfriamiento no puede superar 15ºC/min')])),
                ('tiempo_permanencia', models.FloatField(help_text='Tiempo de permanencia en la temperatura máxima [min]')),
                ('masa_registrar', models.CharField(choices=[('2', 'Masa 2 uma'), ('3', 'Masa 3 uma'), ('4', 'Masa 4 uma')], help_text='Masa a registrar [uma]', max_length=1)),
                ('espesor_muestra', models.FloatField(help_text='Espesor de la muestra [mm]', validators=[django.core.validators.MinValueValidator(0.1, 'El espesor mínimo es 0.1 mm'), django.core.validators.MaxValueValidator(10, 'El espesor máximo es 10 mm')])),
                ('tamaño_muestra', models.FloatField(help_text='Tamaño de la muestra [cm²]', validators=[django.core.validators.MinValueValidator(0.5, 'El tamaño mínimo es 0.5 cm²')])),
                ('geometria_muestra', models.CharField(help_text='Geometría de la muestra (circular, cuadrada, etc.)', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dp_solicitudes_termicas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dp_solicitudes_termicas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Térmica DP',
                'verbose_name_plural': 'Solicitudes Térmicas DP',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DpResultadoTermico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_resultado', models.FileField(help_text='Archivo de resultados (txt o csv)', upload_to='dp_resultados/')),
                ('archivo_resultado_2', models.FileField(blank=True, help_text='Archivo de resultados adicional (opcional)', null=True, upload_to='dp_resultados/')),
                ('fecha_ensayo', models.DateTimeField(help_text='Fecha y hora del ensayo')),
                ('observaciones_tecnico', models.TextField(blank=True, help_text='Observaciones del técnico')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_por_email', models.BooleanField(default=False)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='sigmadp.dpsolicitudtermica')),
            ],
            options={
                'verbose_name': 'Resultado Térmico DP',
                'verbose_name_plural': 'Resultados Térmicos DP',
                'ordering': ['-creado_en'],
            },
        ),
    ]
