# Generated by Django 5.0.1 on 2025-09-21 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmadp', '0002_dpsolicitudtermica_dpresultadotermico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DpAnalisisDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del análisis', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del análisis')),
                ('archivo_datos', models.FileField(help_text='Archivo de datos original', upload_to='dp_analisis/datos/')),
                ('tipo_archivo', models.CharField(choices=[('txt', 'Archivo de texto (.txt)'), ('csv', 'Archivo CSV (.csv)'), ('tsv', 'Archivo TSV (.tsv)'), ('dat', 'Archivo de datos (.dat)')], default='txt', max_length=10)),
                ('separador', models.CharField(default='\t', help_text='Separador de columnas', max_length=10)),
                ('decimal', models.CharField(default=',', help_text='Separador decimal', max_length=5)),
                ('codificacion', models.CharField(default='latin1', help_text='Codificación del archivo', max_length=20)),
                ('mostrar_temperatura', models.BooleanField(default=True, help_text='Mostrar gráfica de temperatura')),
                ('mostrar_leak', models.BooleanField(default=True, help_text='Mostrar gráfica de leak rate')),
                ('mostrar_heater', models.BooleanField(default=True, help_text='Mostrar gráfica de tensión del calefactor')),
                ('mostrar_overview', models.BooleanField(default=True, help_text='Mostrar panel overview')),
                ('archivo_csv_limpio', models.FileField(blank=True, help_text='CSV limpio generado', null=True, upload_to='dp_analisis/csv/')),
                ('archivo_temperatura', models.FileField(blank=True, help_text='Gráfica de temperatura (PNG)', null=True, upload_to='dp_analisis/graficas/')),
                ('archivo_leak', models.FileField(blank=True, help_text='Gráfica de leak rate (PNG)', null=True, upload_to='dp_analisis/graficas/')),
                ('archivo_heater', models.FileField(blank=True, help_text='Gráfica de tensión del calefactor (PNG)', null=True, upload_to='dp_analisis/graficas/')),
                ('archivo_overview', models.FileField(blank=True, help_text='Panel overview (PNG)', null=True, upload_to='dp_analisis/graficas/')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falla')),
                ('duracion_minutos', models.FloatField(blank=True, help_text='Duración del ensayo en minutos', null=True)),
                ('num_muestras', models.IntegerField(blank=True, help_text='Número de muestras', null=True)),
                ('columnas_detectadas', models.TextField(blank=True, help_text='Columnas detectadas en el archivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dp_analisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Datos DP',
                'verbose_name_plural': 'Análisis de Datos DP',
                'ordering': ['-creado_en'],
            },
        ),
    ]
