# Generated by Django 5.0.1 on 2025-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmadp', '0003_dpanalisisdatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpanalisisdatos',
            name='codificacion',
            field=models.CharField(default='cp1252', help_text='Codificación del archivo', max_length=20),
        ),
    ]
