# Generated by Django 5.0.1 on 2025-09-22 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmadp', '0005_dpindicadorcalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpanalisisdatos',
            name='solicitud_termica',
            field=models.ForeignKey(blank=True, help_text='Solicitud termica asociada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_datos', to='sigmadp.dpsolicitudtermica'),
        ),
    ]
