# Generated by Django 5.0.1 on 2026-01-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icts', '0019_merge_20260110_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticsAnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='OpticsEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_reference', models.BooleanField(blank=True, default=False)),
                ('pattern_type', models.CharField(blank=True, max_length=50)),
                ('responsible', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('decommission_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('inventory_number', models.CharField(blank=True, max_length=200)),
                ('measurement_magnitude', models.CharField(blank=True, max_length=200)),
                ('measurement_range', models.CharField(blank=True, max_length=200)),
                ('breakdown_contact', models.TextField(blank=True)),
                ('calibration_acceptance_criteria', models.TextField(blank=True)),
                ('specification_conformity', models.TextField(blank=True)),
                ('associated_equipment', models.TextField(blank=True)),
                ('technical_characteristics', models.TextField(blank=True)),
                ('usage_instructions', models.TextField(blank=True)),
                ('validation_data', models.TextField(blank=True)),
                ('maintenance_required', models.BooleanField(blank=True, default=False)),
                ('maintenance_company', models.CharField(blank=True, max_length=200)),
                ('maintenance_procedure', models.CharField(blank=True, max_length=200)),
                ('maintenance_period', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OpticsAnnualPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('activity', models.CharField(choices=[('MAINTENANCE', 'Mantenimiento'), ('CALIBRATION', 'Calibracion'), ('VERIFICATION', 'Verificacion'), ('VALIDATION', 'Validacion'), ('CONTROL', 'Control')], max_length=30)),
                ('execution_type', models.CharField(choices=[('INTERNAL', 'INTERNO'), ('EXTERNAL', 'EXTERNO')], max_length=10)),
                ('month_01', models.BooleanField(default=False)),
                ('month_02', models.BooleanField(default=False)),
                ('month_03', models.BooleanField(default=False)),
                ('month_04', models.BooleanField(default=False)),
                ('month_05', models.BooleanField(default=False)),
                ('month_06', models.BooleanField(default=False)),
                ('month_07', models.BooleanField(default=False)),
                ('month_08', models.BooleanField(default=False)),
                ('month_09', models.BooleanField(default=False)),
                ('month_10', models.BooleanField(default=False)),
                ('month_11', models.BooleanField(default=False)),
                ('month_12', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sigmaoptics_icts.opticsannualplan')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sigmaoptics_icts.opticsequipment')),
            ],
            options={
                'ordering': ['plan__year', 'equipment_code', 'activity'],
            },
        ),
        migrations.CreateModel(
            name='OpticsAnnualPlanChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COPY', 'Copia'), ('CREATE', 'Creacion'), ('UPDATE', 'Actualizacion'), ('DELETE', 'Borrado')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='sigmaoptics_icts.opticsannualplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='sigmaoptics_icts.opticsannualplanentry')),
            ],
        ),
        migrations.CreateModel(
            name='OpticsEquipmentDocRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='sigmaoptics_icts/equipment/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_refs', to='sigmaoptics_icts.opticsequipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpticsEquipmentIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('operation', models.CharField(max_length=255)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sigmaoptics_icts/equipment/incidents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='sigmaoptics_icts.opticsequipment')),
            ],
        ),
        migrations.CreateModel(
            name='OpticsMaintenanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_activities', to='sigmaoptics_icts.opticsequipment')),
            ],
        ),
        migrations.CreateModel(
            name='OpticsMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField()),
                ('code', models.CharField(blank=True, max_length=100)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='sigmaoptics_icts.opticsequipment')),
            ],
        ),
        migrations.CreateModel(
            name='OpticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_code', models.CharField(blank=True, db_index=True, max_length=16, unique=True)),
                ('report_code', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('reception_date', models.DateField(blank=True, db_index=True, null=True)),
                ('analysis_date', models.DateField(blank=True, db_index=True, null=True)),
                ('report_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('measurement_magnitude', models.CharField(blank=True, max_length=255)),
                ('procedure_code', models.CharField(default='PT-DTF-07', max_length=32)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='sigmaoptics_icts/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optics_sessions', to='icts.accessproposal')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='optics_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpticsSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('identification', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sigmaoptics_icts.opticssession')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('project', models.CharField(blank=True, max_length=255)),
                ('sample_description', models.TextField(blank=True)),
                ('determination', models.CharField(blank=True, max_length=255)),
                ('technique', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='sigmaoptics_icts.opticssession')),
            ],
        ),
    ]
