# Generated by Django 5.0.1 on 2026-01-10 17:54

from django.db import migrations
from django.utils import timezone


def seed_optics_equipment(apps, schema_editor):
    OpticsEquipment = apps.get_model("sigmaoptics_icts", "OpticsEquipment")
    OpticsAnnualPlan = apps.get_model("sigmaoptics_icts", "OpticsAnnualPlan")
    OpticsAnnualPlanEntry = apps.get_model("sigmaoptics_icts", "OpticsAnnualPlanEntry")

    equipment_specs = [
        ("EQ-DTF-L03-02", "Cary Series UV-Vis-Nir Spectrometer"),
        ("EQ-DTF-L03-01", "FTIR (Agilent Cary 630 FTIR)"),
    ]
    equipment_by_code = {}
    for code, description in equipment_specs:
        equipment, _ = OpticsEquipment.objects.get_or_create(
            code=code,
            defaults={"description": description},
        )
        equipment_by_code[code] = equipment

    year = timezone.now().year
    plan, _ = OpticsAnnualPlan.objects.get_or_create(year=year)

    def ensure_entry(equipment, activity, execution_type, month_01=False):
        entry = (
            OpticsAnnualPlanEntry.objects
            .filter(
                plan=plan,
                equipment=equipment,
                activity=activity,
                execution_type=execution_type,
            )
            .first()
        )
        if entry:
            if month_01 and not entry.month_01:
                entry.month_01 = True
                entry.save(update_fields=["month_01"])
            return

        OpticsAnnualPlanEntry.objects.create(
            plan=plan,
            equipment=equipment,
            equipment_code=equipment.code,
            description=equipment.description or equipment.code,
            activity=activity,
            execution_type=execution_type,
            month_01=month_01,
        )

    for equipment in equipment_by_code.values():
        ensure_entry(equipment, "MAINTENANCE", "INTERNAL", month_01=True)
        ensure_entry(equipment, "CONTROL", "INTERNAL", month_01=True)
        ensure_entry(equipment, "CALIBRATION", "EXTERNAL", month_01=False)




class Migration(migrations.Migration):

    dependencies = [
        ('sigmaoptics_icts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_optics_equipment, migrations.RunPython.noop),
    ]
