# Generated by Django 5.0.1 on 2025-09-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sigmalab', '0017_mensajeinterno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfocalSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_trabajo', models.DateTimeField(blank=True, help_text='Fecha y hora de inicio del trabajo en el laboratorio', null=True)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('numero_muestras', models.PositiveIntegerField(default=1, help_text='Número de muestras a procesar')),
                ('tipo_microscopia', models.CharField(choices=[('confocal_laser', 'Microscopía Confocal Láser'), ('confocal_spinning', 'Microscopía Confocal Spinning Disk'), ('super_resolucion', 'Microscopía de Super Resolución'), ('multifoton', 'Microscopía Multifotón'), ('otra', 'Otra')], default='confocal_laser', help_text='Tipo de microscopía confocal requerida', max_length=50)),
                ('longitud_onda_excitacion', models.CharField(blank=True, help_text='Longitud de onda de excitación requerida (nm)', max_length=100)),
                ('longitud_onda_emision', models.CharField(blank=True, help_text='Longitud de onda de emisión esperada (nm)', max_length=100)),
                ('objetivo_requerido', models.CharField(blank=True, help_text='Objetivo requerido (ej: 40x, 63x, 100x)', max_length=100)),
                ('espesor_muestra', models.CharField(blank=True, help_text='Espesor de la muestra (μm)', max_length=50)),
                ('tincion_utilizada', models.TextField(blank=True, help_text='Tinción o marcaje utilizado en la muestra')),
                ('preparacion_muestra', models.TextField(blank=True, help_text='Descripción de la preparación de la muestra')),
                ('material_radioactivo', models.BooleanField(default=False, help_text='¿Es material radiactivo o contaminado?')),
                ('manejo_especial', models.TextField(blank=True, help_text='¿Requiere algún tipo de manejo o protección especial?')),
                ('tratamiento_previo', models.TextField(blank=True, help_text='¿Se ha realizado algún tratamiento previo?')),
                ('procedencia', models.CharField(blank=True, max_length=200)),
                ('otro_dato_importante', models.TextField(blank=True, help_text='Otro dato importante de la muestra')),
                ('requisitos_finales', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('imagen_muestra', models.ImageField(blank=True, help_text='Adjuntar imagen de la muestra', null=True, upload_to='confocal/imagenes/')),
                ('croquis', models.ImageField(blank=True, help_text='Adjuntar croquis', null=True, upload_to='confocal/croquis/')),
                ('tiempo_estimado_numero', models.PositiveIntegerField(blank=True, help_text='Número de unidades de tiempo estimadas (1-30)', null=True)),
                ('tiempo_estimado_unidad', models.CharField(blank=True, choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], help_text='Unidad de tiempo estimada', max_length=10)),
                ('tiempo_estimado_indeterminado', models.BooleanField(default=False, help_text='Marcar si el tiempo de finalización es indeterminado')),
                ('fecha_estimada_finalizacion', models.DateTimeField(blank=True, help_text='Fecha calculada de finalización basada en la estimación', null=True)),
                ('montaje_fluorescente', models.BooleanField(default=False, help_text='Montaje en medio fluorescente')),
                ('fijacion', models.BooleanField(default=False, help_text='Fijación de la muestra')),
                ('deshidratacion', models.BooleanField(default=False, help_text='Deshidratación')),
                ('inclusion', models.BooleanField(default=False, help_text='Inclusión en resina')),
                ('corte_fino', models.BooleanField(default=False, help_text='Corte fino')),
                ('tincion_histologica', models.BooleanField(default=False, help_text='Tinción histológica')),
                ('inmunotincion', models.BooleanField(default=False, help_text='Inmunotinción')),
                ('tincion_nuclear', models.BooleanField(default=False, help_text='Tinción nuclear (DAPI, Hoechst, etc.)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('autonomo', models.BooleanField(default=False, help_text='Usuario validado como autónomo para esta solicitud')),
                ('codigo_muestra', models.CharField(blank=True, help_text='Se puede asignar al aceptar (p.ej. 25-001)', max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('becario_asociado', models.ForeignKey(blank=True, help_text='Becario que realizó la solicitud (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_confocal_realizadas', to='sigmalab.usuarioasociado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_confocal', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_confocal_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud Confocal',
                'verbose_name_plural': 'Solicitudes Confocal',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfocalDiarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('etapa', models.CharField(choices=[('montaje_fluorescente', 'Montaje Fluorescente'), ('fijacion', 'Fijación'), ('deshidratacion', 'Deshidratación'), ('inclusion', 'Inclusión'), ('corte_fino', 'Corte Fino'), ('tincion_histologica', 'Tinción Histológica'), ('inmunotincion', 'Inmunotinción'), ('tincion_nuclear', 'Tinción Nuclear'), ('microscopia', 'Microscopía'), ('procesamiento_imagen', 'Procesamiento de Imagen'), ('otra', 'Otra')], max_length=20)),
                ('nota', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diario', to='sigmaconf.confocalsolicitud')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfocalAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avance', 'Avance'), ('nota', 'Nota interna')], default='avance', max_length=10)),
                ('contenido', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='confocal/avances/')),
                ('visible_para_usuario', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_confocal_publicados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='sigmaconf.confocalsolicitud')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ConfocalMuestraIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_secuencia', models.PositiveIntegerField(help_text='Número de secuencia (1, 2, 3, etc.)')),
                ('identificacion', models.CharField(help_text='Identificación que le da el usuario', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional de la muestra')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='sigmaconf.confocalsolicitud')),
            ],
            options={
                'verbose_name': 'Muestra Individual Confocal',
                'verbose_name_plural': 'Muestras Individuales Confocal',
                'ordering': ['numero_secuencia'],
                'unique_together': {('solicitud', 'numero_secuencia')},
            },
        ),
    ]
