# Generated by ChatGPT on 2025-12-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("icts", "0014_alter_accessproposal_access_code_length"),
        ("sigmaconf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCFYearCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("counter", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["year"],
                "verbose_name": "MCF year counter",
                "verbose_name_plural": "MCF year counters",
            },
        ),
        migrations.CreateModel(
            name="MCFSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lot_code", models.CharField(max_length=20, unique=True)),
                ("report_code", models.CharField(max_length=40, unique=True)),
                ("status", models.CharField(choices=[("in_progress", "In progress"), ("completed", "Completed")], default="in_progress", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("notice_pdf", models.FileField(blank=True, null=True, upload_to="mcf/notices/")),
                ("request_snapshot", models.JSONField(blank=True, default=dict)),
                ("access_proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mcf_sessions", to="icts.accessproposal")),
                ("technician", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="mcf_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "MCF session",
                "verbose_name_plural": "MCF sessions",
            },
        ),
        migrations.CreateModel(
            name="MCFSampleRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("source", models.CharField(choices=[("proposal", "Proposal"), ("session", "Session")], default="proposal", max_length=20)),
                ("identification", models.CharField(max_length=200)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("details", models.TextField(blank=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("analysis_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                ("report_delivery_date", models.DateField(blank=True, null=True)),
                ("operator_name", models.CharField(blank=True, max_length=200)),
                ("roughness", models.BooleanField(default=False)),
                ("image_2d", models.BooleanField(default=False)),
                ("image_3d", models.BooleanField(default=False)),
                ("thickness", models.BooleanField(default=False)),
                ("report_code", models.CharField(blank=True, max_length=40)),
                ("observations", models.TextField(blank=True)),
                ("indicator_i1", models.PositiveSmallIntegerField(default=0)),
                ("indicator_i2", models.PositiveSmallIntegerField(default=0)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="samples", to="sigmaconf.mcfsession")),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("session", "sequence")},
                "verbose_name": "MCF sample record",
                "verbose_name_plural": "MCF sample records",
            },
        ),
    ]
