# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0002_mcf_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcfsession",
            name="final_report_pdf",
            field=models.FileField(blank=True, null=True, upload_to="mcf/final_reports/"),
        ),
        migrations.AddField(
            model_name="mcfsession",
            name="final_report_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcfsession",
            name="final_report_uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="mcf_final_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
