# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("icts", "0014_alter_accessproposal_access_code_length"),
        ("sigmaconf", "0003_mcf_final_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Conversation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_proposal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="lo3_conversation", to="icts.accessproposal")),
            ],
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "LO3 conversation",
                "verbose_name_plural": "LO3 conversations",
            },
        ),
        migrations.CreateModel(
            name="LO3Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at_applicant", models.DateTimeField(blank=True, null=True)),
                ("read_at_technician", models.DateTimeField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="sigmaconf.lo3conversation")),
                ("sender", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "verbose_name": "LO3 message",
                "verbose_name_plural": "LO3 messages",
            },
        ),
        migrations.CreateModel(
            name="LO3MessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="lo3/communications/")),
                ("filename", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="sigmaconf.lo3message")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_message_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
                "verbose_name": "LO3 message attachment",
                "verbose_name_plural": "LO3 message attachments",
            },
        ),
    ]
