# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0004_lo3_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model", models.CharField(blank=True, max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("active", "Active"), ("maintenance", "Maintenance"), ("inactive", "Inactive")], default="active", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "verbose_name": "LO3 equipment",
                "verbose_name_plural": "LO3 equipment",
            },
        ),
        migrations.CreateModel(
            name="LO3EquipmentDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="lo3/equipment/")),
                ("title", models.CharField(max_length=200)),
                ("doc_type", models.CharField(choices=[("manual", "Manual"), ("sop", "SOP"), ("procedure", "Procedure"), ("other", "Other")], default="other", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="sigmaconf.lo3equipment")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_equipment_documents", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LO3 equipment document",
                "verbose_name_plural": "LO3 equipment documents",
            },
        ),
    ]
