# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0005_lo3_equipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Attachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="lo3/attachments/")),
                ("attachment_type", models.CharField(choices=[("photo", "Foto"), ("rawdata", "Raw data"), ("report", "Informe"), ("other", "Otro")], default="other", max_length=20)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sample", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="sigmaconf.mcfsamplerecord")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="sigmaconf.mcfsession")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LO3 attachment",
                "verbose_name_plural": "LO3 attachments",
            },
        ),
        migrations.AddConstraint(
            model_name="lo3attachment",
            constraint=models.CheckConstraint(check=models.Q(("session__isnull", False), ("sample__isnull", False), _connector="OR"), name="lo3_attachment_has_owner"),
        ),
    ]
