# Generated by Codex on 2025-12-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0006_lo3_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Calibration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calibration_type", models.CharField(choices=[("internal", "Internal"), ("external", "External")], default="internal", max_length=20)),
                ("performed_at", models.DateField()),
                ("due_at", models.DateField(blank=True, null=True)),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("certificate_file", models.FileField(blank=True, null=True, upload_to="lo3/calibrations/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calibrations", to="sigmaconf.lo3equipment")),
            ],
            options={
                "ordering": ["-performed_at"],
                "verbose_name": "LO3 calibration",
                "verbose_name_plural": "LO3 calibrations",
            },
        ),
    ]
