# Generated by Codex on 2025-12-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0007_lo3_calibrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3ReferenceMaterial",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("catalog_reference", models.CharField(blank=True, max_length=200)),
                ("responsible", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("reception_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("retired", "Retired")], default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
                "verbose_name": "LO3 reference material",
                "verbose_name_plural": "LO3 reference materials",
            },
        ),
        migrations.CreateModel(
            name="LO3ReferenceMaterialDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="lo3/reference_materials/")),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="sigmaconf.lo3referencematerial")),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LO3 reference material document",
                "verbose_name_plural": "LO3 reference material documents",
            },
        ),
    ]
