# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0008_lo3_reference_materials"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("incident_type", models.CharField(choices=[("control_intermedio", "Control intermedio"), ("incidencia", "Incidencia")], default="incidencia", max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], default="low", max_length=10)),
                ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In progress"), ("closed", "Closed")], default="open", max_length=20)),
                ("corrective_actions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_incidents", to=settings.AUTH_USER_MODEL)),
                ("equipment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidents", to="sigmaconf.lo3equipment")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="incidents", to="sigmaconf.mcfsession")),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LO3 incident",
                "verbose_name_plural": "LO3 incidents",
            },
        ),
        migrations.CreateModel(
            name="LO3IncidentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="lo3/incidents/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("incident", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="sigmaconf.lo3incident")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_incident_attachments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LO3 incident attachment",
                "verbose_name_plural": "LO3 incident attachments",
            },
        ),
    ]
