# Generated by Codex on 2025-12-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sigmaconf", "0009_lo3_incidents"),
    ]

    operations = [
        migrations.CreateModel(
            name="LO3Habilitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("investigator_full_name", models.CharField(blank=True, max_length=200)),
                ("ciemat_id", models.CharField(blank=True, max_length=100)),
                ("department_division", models.CharField(blank=True, max_length=200)),
                ("center_university", models.CharField(blank=True, max_length=200)),
                ("issued_at", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("revoked", "Revoked")], default="active", max_length=20)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                ("certificate_pdf", models.FileField(blank=True, upload_to="lo3/habilitations/")),
                ("equipment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="habilitations", to="sigmaconf.lo3equipment")),
                ("investigator_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_habilitations", to=settings.AUTH_USER_MODEL)),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_habilitations_issued", to=settings.AUTH_USER_MODEL)),
                ("linked_technician_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lo3_habilitations_linked", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-issued_at"],
                "verbose_name": "LO3 habilitation",
                "verbose_name_plural": "LO3 habilitations",
            },
        ),
    ]
